
language: objective-c
xcode_workspace: /InstagramKit-Example/InstagramKit-Example.xcworkspace
xcode_scheme: InstagramKit-Example
# before_install:
#     - gem install cocoapods --quiet
#     - pod --version
#     - pod setup
#     - pod repo update --silent

# script:
    #- pod lib lint
    # - xctool -xcode_workspace InstagramKit-Example/InstagramKit-Example.xcode_workspace -xcode_scheme 'InstagramKit-Example' -configuration Release -sdk iphonesimulator -arch i386 build
